# mysql配置
addr: 127.0.0.1:3306
user: root
pass: 123456
charset : utf8
slave_id: 1001 #slave ID
flavor: mysql #mysql or mariadb
# prometheus配置
#enable_exporter: true #启用prometheus exporter，默认false
#exporter_addr: 9595 #prometheus exporter端口，默认9595
#data_dir: D:\\transfer #应用产生的数据存放地址，默认当前运行目录的store文件夹
logger:
  level: info
#目标类型
target: redis # 支持redis、mongodb、elasticsearch、kafka、rocketmq、NSQ
#redis配置
redis_addrs: 127.0.0.1:6379 #地址，多个用逗号分隔
#redis_group_type: cluster   # 集群类型 sentinel或者cluster
#redis_master_name: mymaster # Master节点名称,如果group_type为sentinel则此项不能为空，为cluster此项无效
#redis_pass: jqkj5350880 #redis密码
#redis_database: 0  #redis数据库 0-16,默认0。如果group_type为cluster此项无效
#rocketmq配置
#rocketmq_name_servers: 192.168.44.113:9876 #rocketmq命名服务地址，多个用逗号分隔
#rocketmq_group_name: transfer_test_group #rocketmq group name,默认为空
#rocketmq_instance_name: transfer_test_group_ins #rocketmq instance name,默认为空
#rocketmq_access_key: RocketMQ #访问控制 accessKey,默认为空
#rocketmq_secret_key: 12345678 #访问控制 secretKey,默认为空

#cluster: # 集群配置
  #name: myTransfer #集群名称，具有相同name的节点放入同一个集群
  # ZooKeeper地址，多个用逗号风格
  #zk_addrs: 192.168.1.10:2181,192.168.1.11:2182,192.168.1.12:2183
  #zk_authentication: 123456 #digest类型的访问秘钥，如：user:password，默认为空
  #etcd_addrs: 192.168.44.113:2379 #etcd连接地址，多个用逗号分隔
  #etcd_user: test #etcd用户名
  #etcd_password: 123456 #etcd密码

#规则配置
rule:
  -
    schema: eseap #数据库名称
    table: t_user #表名称
    #order_by_column: id #排序字段，存量数据同步时不能为空
    #column_lower_case:false #列名称转为小写,默认为false
    #column_upper_case:false#列名称转为大写,默认为false
    column_underscore_to_camel: true #列名称下划线转驼峰,默认为false
    # 包含的列，多值逗号分隔，如：id,name,age,area_id  为空时表示包含全部列
    #include_column: ID,USER_NAME,PASSWORD
    #exclude_column:  # 排除掉的列，多值逗号分隔，如：id,name,age,area_id  默认为空
    #column_mapping: user_name=Uname    #列名称映射，多值逗号分隔，如：user_name=Uname(user_name映射为Uname)
    #default_column_value: pump_type=binlog  #默认的列-值，多个用逗号分隔，如：pump_type=binlog,area_name=合肥
    #date_formatter: yyyy-MM-dd #date类型格式化， 不填写默认yyyy-MM-dd
    #datetime_formatter: yyyy-MM-dd HH:mm:ss #datetime、timestamp类型格式化，不填写默认yyyy-MM-dd HH:mm:ss
    #lua_file_path: lua/t_user.lua   #lua脚本文件，详见使用手册，当此值不为空时后面的配置除redis_structure其余均无效
    #lua_script:   #lua 脚本，详见使用手册，当此值不为空时后面的配置除redis_structure其余均无效
    value_encoder: json  #值编码，支持json、kv-commas、v-commas；默认为json；json形如：{"id":123,"name":"wangjie"} 、kv-commas形如：id=123,name="wangjie"、v-commas形如：123,wangjie
    #value_formatter:  #值格式化表达式，如：${ID}|${USER_NAME},${ID}表示字段id的值、${USER_NAME}表示字段name的值
    #redis相关
    redis_structure: string # 数据类型。 支持string、hash、list、set类型(与redis的数据类型一直)，详见使用手册
    redis_key_prefix: USER_ #key的前缀
    redis_key_column: USER_NAME #使用哪个列的值作为key，不填写默认使用主键
    #redis_key_formatter: {id}-{name} # key格式，如：{id}-{name}；{id}表示字段id的值、{name}表示字段name的值
    #redis_key_value: user #key的值（固定值）；当redis_structure为hash、list、set此值不能为空
    #redis_hash_field_prefix: _CARD_ #hash的field前缀，仅redis_structure为hash时起作用
    #redis_hash_field_column: Cert_No #使用哪个列的值作为hash的field，仅redis_structure为hash时起作用，不填写默认使用主键
    #rocketmq相关
    #rocketmq_topic: transfer_test_topic #rocketmq topic,不能为空